/*
 * global_define.h
 *
 *  Created on: 2026. 5. 8.
 *      Author: ADJ
 */

#ifndef AUDIO_FRAME_GLOBAL_DEFINE_H_
#define AUDIO_FRAME_GLOBAL_DEFINE_H_

#include <stdint.h>

typedef enum
{
	AUDIO_SRC_USB = 0,
	AUDIO_SRC_AUX,
	AUDIO_SRC_BT
} AudioSource_t;

#define MASTER_BLOCK_SIZE 256

// 에러 코드
typedef enum
{
	AUDIO_ERR_INPUT_OVERFLOW = 0,
	AUDIO_ERR_INPUT_UNDERFLOW,

	AUDIO_ERR_OUTPUT_OVERFLOW,
	AUDIO_ERR_OUTPUT_UNDERFLOW,

	AUDIO_ERR_FFT_OVERFLOW,
	AUDIO_ERR_FFT_UNDERFLOW,

	AUDIO_ERR_ADC_AUX_START_FAIL,
	AUDIO_ERR_ADC_AUX_STOP_FAIL,
	AUDIO_ERR_ADC_AUX_TIM_START_FAIL,
	AUDIO_ERR_ADC_AUX_TIM_STOP_FAIL,

	AUDIO_ERR_ADC_VREG_START_FAIL,
	AUDIO_ERR_ADC_VREG_STOP_FAIL,
	AUDIO_ERR_ADC_VREG_TIM_START_FAIL,
	AUDIO_ERR_ADC_VREG_TIM_STOP_FAIL,

	AUDIO_ERR_I2S_RX_START_FAIL,
	AUDIO_ERR_I2S_RX_STOP_FAIL,

	AUDIO_ERR_I2S_TX_START_FAIL,
	AUDIO_ERR_I2S_TX_STOP_FAIL,

	AUDIO_ERR_COUNT

} AudioErrorCode_t;

#endif /* AUDIO_FRAME_GLOBAL_DEFINE_H_ */
